[package]
name = "minions"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { workspace = true }
rand = { workspace = true }

pixelate = { path = "../pixelate" }
entities = { path = "../entities" }
input = { path = "../input" }
assets = { path = "../assets" }